services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my_network
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg-isready -h db -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py csu && python manage.py collectstatic --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - my_network
    env_file:
      - .env

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web
    dns:
      - 127.0.0.11
    networks:
      - my_network
    env_file:
      - .env

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume: