# Generated by Django 5.1.7 on 2025-04-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0002_alter_reservation_user_feedback'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='unique_reservation',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
