# Generated by Django 5.1.7 on 2025-04-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0003_remove_reservation_unique_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Укажите имя гостя', max_length=255, null=True, verbose_name='Имя гостя'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Укажите время и дату окончания бронирования', null=True, verbose_name='Время и дата окончания бронирования'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Укажите номер телефона', max_length=255, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='Укажите время и дату начала бронирования', null=True, verbose_name='Время и дата начала бронирования'),
        ),
    ]
