# Generated by Django 5.1.7 on 2025-04-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0004_alter_reservation_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='quantity_customers',
            field=models.PositiveIntegerField(blank=True, help_text='Укажите количество гостей', null=True, verbose_name='Количество гостей'),
        ),
    ]
