# Generated by Django 5.1.7 on 2025-04-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0007_alter_reservation_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images', verbose_name='Фото меню')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='poster_images', verbose_name='Фото афиши')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Афиша',
                'verbose_name_plural': 'Афиша',
            },
        ),
    ]
